### ISSUE TITLE
ARC Semantic Issue (Xcode): No known class method for selector 'startSdkWithAppId:appKey:appSecret:delegate:'

### ISSUE THREAD

**Issue by muyuballs** [Wayaer/flutter_getui#3]
flutter: 2.10.3
plugin: 2.2.0
ARC Semantic Issue (Xcode): No known class method for selector 'startSdkWithAppId:appKey:appSecret:delegate:'

**Comment by shenlanchenwei** [comment]
+1

**Comment by shenlanchenwei** [comment]
![image](https://user-images.githubusercontent.com/6754634/161181343-e167ad2c-1591-4437-8846-23460fbfe555.png)

**Comment by Wayaer** [comment]
2.3.0

**Comment by shenlanchenwei** [comment]
@Wayaer 谢谢
