### ISSUE TITLE
iOS的setTag方法错误

### ISSUE THREAD

**Issue by SkyOfFeather** [Wayaer/flutter_getui#4]
iOS与Flutter交互代码处有错，安卓没留意。

Flutter处调用SetTag传入了一个map，iOS原生接收处调用[GeTuiSDK SetTags:]，接收参数应该是数组，却把flutter的arguments给了方法，导致传入的是个dict，正确写法如下：
`if([@"setTag" isEqualToString:call.method]) {
        NSDictionary *info = call.arguments;
        NSArray *tags = info[@"tags"];
        NSString *sn = info[@"sn"];
        if (sn && sn.length > 0) {
            result([NSNumber numberWithBool:[GeTuiSdk setTags:tags andSequenceNum:sn]]);
        }else {
            result([NSNumber numberWithBool:[GeTuiSdk setTags:tags]]);
        }
    }`

另外[GeTuiSdk setTags:]方法返回的布尔值，并不能说明设置标签成功或失败了，个推有独立的监听setTag方法是否成功的方法：【GeTuiSdkDidSetTagsAction:(NSString *)sequenceNum result:(BOOL)isSuccess error:(nullable NSError *)aError】
只有这个方法可以监听setTag的结果

**Comment by Wayaer** [comment]
已经修改了部分api 更新下版本 3.0.0 吧
